.travis.yml
CHANGES.rst
dask_geomodeling/config.py
dask_geomodeling/core/graphs.py
dask_geomodeling/geometry/aggregate.py
dask_geomodeling/geometry/base.py
dask_geomodeling/geometry/field_operations.py
dask_geomodeling/geometry/parallelize.py
dask_geomodeling/geometry/sources.py
dask_geomodeling/geometry/text.py
dask_geomodeling/raster/misc.py
dask_geomodeling/raster/sources.py
dask_geomodeling/raster/temporal.py
dask_geomodeling/tests/test_core.py
dask_geomodeling/tests/test_geometry.py
dask_geomodeling/tests/test_raster.py
setup.py

This is 'part of the deal' with open source code: testing against a version matrix! I solved some issues, namely with Py3.6 syntax (we want to support Py3.5).
Testing is done on OSX and Linux, using conda.

[Done] Travis + version compatibiltity fixes

---

CHANGES.rst
dask_geomodeling/raster/elemwise.py
dask_geomodeling/raster/misc.py
dask_geomodeling/raster/sources.py
dask_geomodeling/tests/test_raster.py
dask_geomodeling/tests/test_raster_misc.py

https://nelen-schuurmans.atlassian.net/browse/BACK-249

Fix propagation of 'extent' through raster.Clip

---

CHANGES.rst
README.rst
appveyor.yml
dask_geomodeling/raster/sources.py
dask_geomodeling/tests/test_core.py
dask_geomodeling/tests/test_raster_sources.py
dask_geomodeling/tests/test_utils.py

Appveyor doesn't list this repo yet as an option to add. I will try again later.

Add appveyor script

---

docs/installation.rst

The `--` in `--add`  is shown as ­an emdash instead of a double dash, for instance :-)

rst syntax fix

---

CHANGES.rst
dask_geomodeling/raster/misc.py
dask_geomodeling/tests/test_raster_misc.py

https://nelen-schuurmans.atlassian.net/browse/BACK-644

RasterizeWKT

---

dask_geomodeling/geometry/aggregate.py
dask_geomodeling/tests/test_geometry.py

https://nelen-schuurmans.atlassian.net/browse/BACK-720

Fix AggregateRaster: it now returns NaN for no data pixels

---

CHANGES.rst
dask_geomodeling/geometry/field_operations.py
dask_geomodeling/tests/test_geometry.py

https://nelen-schuurmans.atlassian.net/browse/BACK-730

Fixes in classify / classifyfromcolumns

---

CHANGES.rst
dask_geomodeling/raster/elemwise.py
dask_geomodeling/tests/test_raster.py

https://nelen-schuurmans.atlassian.net/browse/BACK-774

Fixed bug in FillNoData block

---

.gitignore
CHANGES.rst
dask_geomodeling/geometry/aggregate.py
dask_geomodeling/tests/test_geometry.py

https://nelen-schuurmans.atlassian.net/browse/BACK-817

PR #37 messed up the indices in AggregateAboveThreshold 

---

CHANGES.rst
dask_geomodeling/geometry/sinks.py
dask_geomodeling/tests/test_geometry_sinks.py

https://nelen-schuurmans.atlassian.net/browse/BACK-875

Accept categorical values in GeometryFileSink

---

CHANGES.rst
dask_geomodeling/raster/misc.py
dask_geomodeling/tests/test_raster.py
dask_geomodeling/tests/test_utils.py
dask_geomodeling/utils.py

https://nelen-schuurmans.atlassian.net/browse/BACK-373

Geoblock mask int values cannot be higher then uint8

---

.travis.yml
CHANGES.rst
dask_geomodeling/geometry/sources.py
dask_geomodeling/raster/spatial.py
dask_geomodeling/tests/test_raster.py
dask_geomodeling/tests/test_raster_spatial.py
dask_geomodeling/utils.py

Closes https://github.com/nens/lizard-nxt/issues/3706

Fix point requests for smooth geoblock

---

CHANGES.rst
dask_geomodeling/raster/spatial.py
dask_geomodeling/tests/test_raster_spatial.py

I hoped that I could resolve https://github.com/nens/lizard-nxt/issues/4491 with this fix, but it appears to be something different. Still, there is work done :)

Allow no coordinates in Place geoblock

---

CHANGES.rst
dask_geomodeling/raster/temporal.py
dask_geomodeling/tests/test_raster.py

I actually looked at nanprod, nanargmin and nanargmax too, but they each have additional difficulties so I left them out

Add var and std statistics

---

CHANGES.rst
dask_geomodeling/geometry/field_operations.py
dask_geomodeling/tests/test_geometry.py

This addresses bugs issues #76 and #74

Do not return categoricals from Classify

---

CHANGES.rst
dask_geomodeling/geometry/field_operations.py
dask_geomodeling/tests/test_geometry.py

Fix mask/where with non-boolean conditionals

---

CHANGES.rst
dask_geomodeling/raster/spatial.py

Make Dilate arguments JSON serializable

---

dask_geomodeling/geometry/field_operations.py

Reverts nens/dask-geomodeling#82

Revert "[Done] Fix Classify still returns categorical in some cases"

---

CHANGES.rst
dask_geomodeling/geometry/field_operations.py
dask_geomodeling/tests/test_geometry.py

Fix Classify categorical

---

.github/workflows/test-conda.yaml
CHANGES.rst
dask_geomodeling/__init__.py
dask_geomodeling/raster/sources.py
dask_geomodeling/tests/test_raster_sources.py
setup.py

It is possible since 2.5.1, but apparently still not allowed.

Allow and test raster source reprojecting.
